### ISSUE TITLE
(Group) Create a system where the player's gravity is affected by a gravity generator

### ISSUE THREAD

**Issue by Migs** [niu-gdo/IGDO-Fall-2023-Project#8]
Create a script that has a generators information stored in it. (Alternatively, you can use a ScriptableObject for this)
- Consider these attributes
- Gravity Direction
- Gravity field strength
- Health

Create (or update) a script that reduces or increases the plauyer's velocity based on the Gravity Field Strength emiited by the gravity generator.

Create a script adding fall damage to the player affected by fall distance/time and gravity strength.

Create a script that changes the players upward position based on the Gravity Direction emiited by the generator

**Comment by Nmerryman** [comment]
# Step s 
- make a shape that changes gravity when touching it
- Change it to work with actually physics in the areas?
